#!/usr/bin/python

from pygaff.conf import API_URI, API_USERNAME, API_PASSWORD
import pygaff.compile
import pygaff.api

api = pygaff.api.WikiAPI (API_URI, API_USERNAME, API_PASSWORD)
api.login()
compiler = pygaff.compile.WorldCompiler (api)
world = compiler.compile()
exporter = pygaff.api.WorldJSONExporter (world)
print exporter.to_string()
