#!/usr/bin/python

from pygaff.conf import API_URI, API_USERNAME, API_PASSWORD
import pygaff.compile
import pygaff.exporter
import pygaff.api
import pygaff.log

import sys

log = pygaff.log.EventLogger (info=[sys.stdout],error=[sys.stderr],warning=[sys.stderr],debug=[sys.stdout])
#log = pygaff.log.EventLogger (info=[],error=[],warning=[],debug=[])
api = pygaff.api.WikiAPI (API_URI, API_USERNAME, API_PASSWORD)
api.login()
compiler = pygaff.compile.WorldCompiler (api, log=log)
world = compiler.compile()
exporter = pygaff.exporter.WorldJSONExporter (world)

if '-p' in sys.argv:
    print exporter.to_string()

