#!/usr/bin/python

from gaff.conf import API_URI, API_USERNAME, API_PASSWORD
import gaff.compile
import gaff.exporter
import gaff.api
import gaff.log

import sys

log = gaff.log.EventLogger (info=[sys.stdout],error=[sys.stderr],warning=[sys.stderr],debug=[sys.stdout])
#log = gaff.log.EventLogger (info=[],error=[],warning=[],debug=[])
api = gaff.api.WikiAPI (API_URI, API_USERNAME, API_PASSWORD)
api.login()
compiler = gaff.compile.WorldCompiler (api, log=log)
world = compiler.compile()
exporter = gaff.exporter.WorldJSONExporter (world)

if '-p' in sys.argv:
    print exporter.to_string()

